version: '3'
services:
   elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1 
    environment:
            - discovery.type=single-node
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data 
   db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" 
   app: 
     build: .
     command: bundle exec rails s -p 3000 -b '0.0.0.0'
     volumes: 
       - ".:/app"
     ports: 
       - "3001:3000"
     depends_on:
       - db
       - elasticsearch
     links:
       - db
       - elasticsearch
     environment:
       DB_USER: root
       DB_NAME: app
       DB_PASSWORD: password
       DB_HOST: db  
volumes:
   elasticsearch:
   
 