version: '3'
services:
   elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1 
    environment:
            - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300" 
   db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - "db:/var/run/mysqld"  
   redis:
    image: "redis:4.0-alpine"
    command: redis-server
    volumes:
      - "redis:/data"
   app: 
     build: .
     command: ["/bin/sh", "bin/docker-start"]
     volumes: 
       - "/app"
     ports: 
       - "3000:3000"
     depends_on:
       - db
       - elasticsearch
       - redis
     links:
       - db
     restart: always
     environment:
       DB_USER: root
       DB_NAME: app
       DB_PASSWORD: password
       DB_HOST: db
       ELASTICSEARCH_URL: elasticsearch
       REDIS_HOST: redis://redis:6379/0
       REDIS_PORT: 6379/0
       REDIS_DB: 0
       REDIS_URL_SIDEKIQ: redis://redis:6379/1
   sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq -q default -c 10
    volumes: 
      - "/app"
      - "db:/var/run/mysqld"
    environment:
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
      ELASTICSEARCH_URL: elasticsearch
volumes:
  redis:
  db: