# Sample configuration file for Sidekiq.
  # Options here can still be overridden by cmd line args.
  # Place this file at config/sidekiq.yml and Sidekiq will
  # pick it up automatically.
---
:verbose: false
:concurrency: 1
:timeout: 25

:queues:
  - default
production:
  :concurrency: 25
staging:
  :concurrency: 15